"""
Post-bake distribution check against the 4 pre-registered expectations:
  1. all four infield lanes within noise of zero (per-position range_gb sum)
  2. 3B spread comes back widest / near-widest of the infield (SD of drs_floor)
  3. IF p90 meaningfully positive, max in the low twenties (regressed drs_floor)
  4. (seam check is a separate instrumented pass)
Reads output/player_season_defense.csv (regenerated by run_drs.py with the baked calibration).
"""
import csv, math

def stats(v):
    v = sorted(v); n = len(v)
    if not n: return None
    q = lambda p: v[min(n - 1, int(p * (n - 1)))]
    s = sum(v); m = s / n
    sd = math.sqrt(sum((x - m) ** 2 for x in v) / n)
    return dict(n=n, sum=s, mean=m, sd=sd, min=q(0), p10=q(.1), med=q(.5), p90=q(.9), max=q(1))

def main():
    rows = list(csv.DictReader(open("output/player_season_defense.csv")))
    f = lambda r, k: float(r[k]) if r.get(k) not in (None, "", "None") else 0.0

    IF = ["3B", "SS", "2B", "1B"]
    print("=== (1) lane zero check: range_gb sum by position ===")
    for pos in ["3B", "SS", "2B", "1B", "C", "P", "LF", "CF", "RF"]:
        g = [f(r, "range_gb") for r in rows if r["position"] == pos]
        if g: print(f"  {pos:<4} sum {sum(g):+8.0f}   n {len(g)}")

    print("\n=== (3) drs_floor distribution by infield position (regressed, per-player) ===")
    print("  pos    n   sum    mean    min    p10    med    p90    max")
    for pos in IF:
        st = stats([f(r, "drs_floor") for r in rows if r["position"] == pos])
        if not st: continue
        print(f"  {pos:<4} {st['n']:4d} {st['sum']:6.0f}  {st['mean']:+.2f}  "
              f"{st['min']:+6.1f} {st['p10']:+5.1f} {st['med']:+5.1f} {st['p90']:+5.1f} {st['max']:+5.1f}")
    ifrows = [f(r, "drs_floor") for r in rows if r["position"] in IF]
    st = stats(ifrows)
    print(f"\n  IF aggregate drs_floor:  p90 {st['p90']:+.2f}   max {st['max']:+.1f}   "
          f"min {st['min']:+.1f}   mean {st['mean']:+.2f}   (expect: p90 >0, max low-20s)")

    # (2) SPREAD PER CHANCE — the honest difficulty test. Raw SD is volume-contaminated (SS sees
    # more balls), so we compare SD of range_gb PER grounder chance. bip_opps for an infielder is
    # ~all grounders, so it's the chance proxy. Reported next to raw SD + mean chances + a
    # noise-robust chance-weighted SD, so the read is a yes/no, not an interpretation.
    print("\n=== (2) SPREAD PER CHANCE by lane (min 40 chances) ===")
    print("  pos    n   mean_chances   raw_SD(range_gb)   per-chance SD   (widest per-chance = difficulty shows)")
    perchance = {}
    for pos in IF:
        pl = [(f(r, "range_gb"), f(r, "bip_opportunities")) for r in rows
              if r["position"] == pos and f(r, "bip_opportunities") >= 40]
        if not pl: continue
        rawsd = stats([g for g, _ in pl])["sd"]
        rates = [g / o for g, o in pl]
        # chance-weighted SD of the per-chance rate (down-weights noisy low-chance players)
        W = sum(o for _, o in pl); mu = sum(g for g, _ in pl) / W
        wsd = math.sqrt(sum(o * (g / o - mu) ** 2 for g, o in pl) / W)
        mc = sum(o for _, o in pl) / len(pl)
        perchance[pos] = wsd
        print(f"  {pos:<4} {len(pl):4d}   {mc:7.1f}       {rawsd:7.2f}          {wsd:.4f}")
    widest = max(perchance, key=perchance.get)
    print(f"  -> widest PER-CHANCE spread: {widest}   (expectation: 3B widest/near-widest)")

    # infield range leaderboard — the eye-test handoff (NOT a criterion). First honest infield
    # numbers of the project: names should skew to regulars at real programs with healthy chance
    # counts, not small-sample flukes. drs_floor is the regressed range value; raw range_gb + chances
    # shown so a thin denominator is visible.
    print("\n=== INFIELD RANGE LEADERBOARD (top 10 by drs_floor; eye-test, not a criterion) ===")
    ir = [r for r in rows if r["position"] in IF]
    ir.sort(key=lambda r: -f(r, "drs_floor"))
    print("  player                team  pos   drs_floor  raw range_gb  chances")
    for r in ir[:10]:
        print(f"  {(r.get('player') or '?')[:20]:<20}  {(r.get('team') or '')[:4]:<4}  {r['position']:<3}   "
              f"{f(r,'drs_floor'):+7.2f}   {f(r,'range_gb'):+7.1f}   {f(r,'bip_opportunities'):6.0f}")

    # conservation of the relocation — EXACT per-position targets (raw xAVG·RPP, uncalibrated):
    #   P must equal +1511, C must equal +60. The sum is not the test; a 60-run leak must not hide.
    print("\n=== conservation: relocated pitcher_fielding (exact targets P=+1511, C=+60) ===")
    for pos, tgt in [("P", 1511), ("C", 60)]:
        pf = sum(f(r, "pitcher_fielding") for r in rows if r["position"] == pos)
        ok = "OK" if abs(pf - tgt) <= 1 else "!! MISMATCH"
        print(f"  {pos}: {pf:+.0f}   (target {tgt:+d})   {ok}")

if __name__ == "__main__":
    main()
