project_id = "kfkuhdmpchxyffmnowgj"

[functions.google-sheets-sync]
verify_jwt = false

[functions.recalculate-prediction]
verify_jwt = false

[functions.csv-bulk-import]
verify_jwt = false

[functions.scrape-64analytics]
verify_jwt = false

[functions.update-player-teams]
verify_jwt = false