project_id = "kfkuhdmpchxyffmnowgj"

[functions.google-sheets-sync]
verify_jwt = false

[functions.recalculate-prediction]
verify_jwt = false

[functions.csv-bulk-import]
verify_jwt = false

[functions.scrape-64analytics]
verify_jwt = false

[functions.update-player-teams]
verify_jwt = false

[functions.import-rate-csv]
verify_jwt = false

[functions.scrape-2026-rosters]
verify_jwt = false

[functions.check-departed-csv]
verify_jwt = false

[functions.scan-silent-transfers]
verify_jwt = false

[functions.fill-blank-stats]
verify_jwt = false

[functions.fill-blank-scouting]
verify_jwt = false

[functions.reconcile-2025-teams]
verify_jwt = false

[functions.import-power-ratings-csv]
verify_jwt = false

[functions.scrape-team-conferences]
verify_jwt = false
