-- WAR-recalibration Phase A gap-fill (2026-08-26).
-- These columns exist on STAGING (added ad-hoc during the recalibration work) but had NO
-- committed migration, so the prod runbook listed them with nothing to run. Generated by
-- diffing staging's information_schema against prod for the three affected tables; types
-- match staging exactly (float8→double precision, numeric, timestamptz). Additive + idempotent.
--   Conference Stats: run_env_factor + hitter_talent_plus (Bucket B), updated_at.
--     (era_plus..hr9_plus are in 20260821000000_conf_pitcher_env_plus.sql.)
--   Park Factors: the 10 *_seasonal columns + updated_at. (No era_factor/fip_factor — the code
--     reuses rg_factor; staging has no such columns.)
--   pitch_log_pitcher_totals: ip (IP for the totals rollup).

alter table "Conference Stats"
  add column if not exists updated_at         timestamptz,
  add column if not exists run_env_factor     double precision,
  add column if not exists hitter_talent_plus double precision;

alter table "Park Factors"
  add column if not exists updated_at              timestamptz,
  add column if not exists avg_factor_seasonal     double precision,
  add column if not exists obp_factor_seasonal     double precision,
  add column if not exists iso_factor_seasonal     double precision,
  add column if not exists rg_factor_seasonal      double precision,
  add column if not exists lhb_avg_factor_seasonal double precision,
  add column if not exists lhb_obp_factor_seasonal double precision,
  add column if not exists lhb_iso_factor_seasonal double precision,
  add column if not exists rhb_avg_factor_seasonal double precision,
  add column if not exists rhb_obp_factor_seasonal double precision,
  add column if not exists rhb_iso_factor_seasonal double precision;

alter table pitch_log_pitcher_totals
  add column if not exists ip numeric;
