// This file is automatically generated. Do not edit it directly.
// 2026-05-14: extended to support Node CLI mode (service-role key from process.env).
// Browser path uses the original Vite-injected anon key + localStorage; Node path
// uses the SUPABASE_SERVICE_ROLE_KEY env var (set via .env.local) and disables auth.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const IS_NODE = typeof window === "undefined" && typeof process !== "undefined" && !!process.versions?.node;

let SUPABASE_URL: string;
let SUPABASE_KEY: string;
let supabaseClient: SupabaseClient<Database>;

if (IS_NODE) {
  const env = process.env;
  SUPABASE_URL = (env.SUPABASE_URL || env.VITE_SUPABASE_URL) ?? "";
  SUPABASE_KEY = (env.SUPABASE_SERVICE_ROLE_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY) ?? "";
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    throw new Error(
      "Node CLI requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in ~/dev-main/diamond-predictor-66/.env.local",
    );
  }
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });
} else {
  SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const supabase = supabaseClient;
